code/linalg.c, code/ndarray.c, code/poly.c
Using the original code, attempting to compile on macOS using `clang` would fail. There were three types of error that were raised:
* In `ndarray.c` there were three occurrences of the condition of `if` statements being an equality comparison surrounded by double parentheses. This raises a warning (treated as an error due to compilation with `-Werror`) because use of double parentheses is a standard idiom for _suppressing_ the warning about use of an assignment in a condition. This was fixed by removing the excess parentheses.
* In `linalg.c` there were three cases of `abs()` being called with a floating point value and the result being compared to a floating point value, even though `abs()` takes and returns `int` values. This was replaced with calls to `fabs` as used elsewhere in the …
=> Fixed several issues preventing compilation on macOS

code/ndarray.c, code/ndarray.h, code/ulab.c
.. this makes ndarray.rawbytes redundant.  Circuitpython will remove it.
=> ndarray: let memoryview(arr) work

code/fft.c, code/filter.c, code/linalg.c, code/ndarray.c, code/ndarray.h, code/numerical.c, code/poly.c, code/vectorise.c
Testing performed: Built both circuitpython (ulab PR branch, unix port) and micropython (master branch, unix port) with the same ulab sources.  Ran basic smoketest of creating an ndarray via the ulab.array constructor, including dtype keyword argument.
=> Make portable to CircuitPython within same codebase

README.md
Since the micropython.mk file has added the following line
```
CFLAGS_EXTRA = -DMODULE_ULAB_ENABLED=1
```
There's no need to add #define MODULE_ULAB_ENABLED (1) in the mpconfigport.h.Or it would make redefined errors while compiling code.
=> Deleting "#define MODULE_ULAB_ENABLED (1)"

.github/workflows/build.yml
This PR modifies the workflow trigger, so that CI runs only, if files in either code/, or tests/ change. With that, updates to the documentation would not consume github resources.
=> include only code changes in workflow file

code/extras.c, code/extras.h, code/fft.c, code/fft.h, code/linalg.h, code/ulab.h
`spectrum` is moved from `fft` to the `extras` module. If `spectrum` is desired, `fft` must be included in `ulab.h`. @jepler can you suggest a more elegant separation (one that takes the dependence on `fft` automatically into account)?
=> moved spectrum to extras module

code/ndarray.c
In CircuitPython (only), a the slice assignment to [-1:-1:-3] of an ndarray of length 1 caused a crash.  This appears to be because in CircuitPython, the internal pointer of an empty array was NULL rather than pointing at some memory which happened to be valid and assignable.
This appears to be a corner case of how integer promotion rules work in C. The expression `slice.stop - slice.start + (slice.step + correction)` is type `unsigned long` and on a LP64 platform its value is 18446744073709551614.  This led to the function returning that this slice had length 1 instead, during the automated tests.
By casting to signed types capable of holding indices and sizes, the problem is corrected on both platforms.
=> slice_length: avoid implementation-defined division by negative number

code/ndarray.c, code/ulab.c, docs/manual/source/conf.py, docs/manual/source/ulab.rst, docs/ulab-change-log.md, docs/ulab-manual.ipynb
This modification adds the fast initialisation option the `ndarray_make_new_core`, namely, if an ndarray is initialised from another ndarray, and the dtypes are identical, then the contents will simply be copied without inspection, iteration, etc. This should be significantly faster than the old method.
=> added fast initialisation option to ndarray_make_new_core, and updated docs

code/numerical.c
@jepler This should fix https://github.com/v923z/micropython-ulab/issues/34.
=> contraction returns scalar, if dimension is 0

code/ndarray.c, code/ndarray.h, code/ulab.c, docs/ulab-change-log.md
The implementation of `**` should answer the feature request in https://github.com/v923z/micropython-ulab/issues/14#issuecomment-605499572. Reversed operators (i.e., when the `ndarray` stands on the right hand side of an operator, as in 
```
a = array([1, 2, 3])
a + 1
1 + a
```
were requested a long time ago. 
A couple of examples: 
```
import ulab
a = ulab.array(range(10), dtype=ulab.int8)
print(1+a, a+1)
print(2*a, a*2)
print(2**a, a**2)
print(a-1, 1-a)
print(a/2, 2/a)
```
=> adds an implementation of the `**` binary operator, and the reversed binary operators

code/ulab.c
#84 makes use of a recently added micropython feature.  Use preprocessor tests to restore compatibility when building in CircuitPython.
=> Restore circuitpython compatibility after #84

code/poly.c
* In the 3-args case, the lengths of the arguments were not checked
* in the 3-args case, the type of the 2nd argument was not checked
* gcc falsely diagnosed a `maybe-uninitialized` variable because it did not see that the branches of the if() statement were mutually exclusive
It's this third issue that originally drew my attention to this code, adafruit/circuitpython#2787
=> polyfit: Argument handling improvements

code/poly.c
Reverts v923z/micropython-ulab#101
@jepler This is really odd: your checks passed, but after merging it, ulab doesn't compile anymore, and shows symptoms mentioned in https://github.com/v923z/micropython-ulab/issues/102. Unfortunately, I won't have time to fix this till around 2000 GMT. Something must have changed upstream in `micropython` in the meantime.
=> Revert "polyfit: Argument handling improvements"

code/ulab.h
Perhaps I'm overlooking something, but when I tried to _actually_ disable a module by adding
`#define ULAB_COMPARE_MODULE (0)` in an mpconfigboard.h, I got multiple diagnostics like
```
../../extmod/ulab/code/ulab.h:37: error: "ULAB_COMPARE_MODULE" redefined [-Werror]
```
Therefore, in ulab.h, check whether the enabling-symbol is defined or not before defining it to (1) to enable everything by default.
This is not done for ULAB_CREATE_MODULE since, as the comments note, it is always enabled.
We may need to use this in CircuitPython soon because, at the moment, adding ulab.compare overflows one build, the espruino pico (stm).  See adafruit/circuitpython#2811 for progress integrating the current (or now slightly old :frowning:) ulab.
=> ulab.h: Actually allow excluding modules

README.md, code/compare.c, code/compare.h, code/ulab.c, docs/manual/source/conf.py, docs/manual/source/ulab.rst, docs/ulab-change-log.md, docs/ulab-manual.ipynb
This PR offers a workaround for the issue mentioned in https://github.com/v923z/micropython-ulab/pull/86. The `equal` and `not_equal` functions are simply a wrapper for `==`, and `!=`, hence, on `micropython` they deliver identical results, while on `circuitpython`, only `equal/not_equal` yield `numpy`-compatible behaviour, because the `==`, and `!=` operators can't be resolved correctly for non-native types (`ndarray` in this case).
Successfully tested on `circuitpython`'s unix port.
Use cases are listed in the documentation under https://github.com/v923z/micropython-ulab/blob/equal/docs/manual/source/ulab.rst#equal-not_equal
@jepler @dhalbert @tannewt
=> added equal/not_equal to compare.c

code/ndarray.c, code/ndarray.h, code/ulab.c, docs/manual/source/conf.py, docs/manual/source/ulab.rst, docs/ulab-manual.ipynb
This PR adds formatting options to `ndarray`s printouts, and implements the feature request in https://github.com/v923z/micropython-ulab/issues/113. 
@jepler I think this is a useful addition, and I have meant to add this feature for a long time. I have tested it on `circuitpython`'s unix port, and haven't seen any glitches. If it is otherwise OK, you can merge it. Documentation is in https://github.com/v923z/micropython-ulab/blob/print/docs/manual/source/ulab.rst#customising-array-printouts Thanks!
=> added set_printoptions/get_printoptions functions

code/approx.c, code/ndarray.h, code/vectorise.c
This fixes the following build error when updating ulab in CircuitPython:
```
../../extmod/ulab/code/vectorise.c: In function 'vectorise_vectorized_function_call':
../../extmod/ulab/code/vectorise.c:242:15: error: implicit declaration of function 'mp_obj_is_int'; did you mean 'mp_obj_list_init'? [-Werror=implicit-function-declaration]
242 |     } else if(mp_obj_is_int(args[0]) || mp_obj_is_float(args[0])) {
|               ^~~~~~~~~~~~~
|               mp_obj_list_init
../../extmod/ulab/code/vectorise.c:242:15: error: nested extern declaration of 'mp_obj_is_int' [-Werror=nested-externs]
cc1: all warnings being treated as errors
```
=> Updates needed to build latest code on CircuitPython

.github/workflows/build.yml
I noticed on #122 that no actions were run.  I believe this is because the paths directives had no wildcards, contrary to the examples at https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
Eliminating the paths: restrictions entirely may be an equally valid course of action.
=> github actions: Fix paths directives

code/micropython.mk
ulab not compatible with enabling '_thread' module from the make command :
- building ulab with thread enabled in MicroPython :
`$ make -j8 CFLAGS_EXTRA='-DMICROPY_PY_THREAD=1' BOARD=PYBV11 USER_C_MODULES=../../../ulab all`
yields a firmware with '_thread' module but without 'ulab' module, because 'CFLAGS_EXTRA' is used in the make command and in 'ulab/code/micropython.mk', so the value of the last is ignored;
- the solution is to use 'override' and '+=' in in last line of 'ulab/code/micropython.mk' :
`override CFLAGS_EXTRA += -DMODULE_ULAB_ENABLED=1`
Another solution would be enabling '_thread' module by editing MicroPython source code, "../micropython/ports/stm32/mpconfigport.h", line 133, chaning to '#define MICROPY_PY_THREAD           (1)', so no changes to ulab source code.
But it is …
=> fixed incompatibility when enabling '_thread' module from the make command

code/extras.h, code/vectorise.h
The [ulab issue #135 "Incompatibility between gcc-arm 10.1 and ulab+MicroPython"](https://github.com/v923z/micropython-ulab/issues/135) can be fixed, following @v923z suggestion, by adding 'extern' in :
- "ulab/code/extras.h", line 21, so it becomes :
`extern mp_obj_module_t ulab_extras_module;`
- "ulab/code/vectorise.h", line 27, so it becomes :
`extern mp_obj_module_t ulab_vectorise_module;`
So gcc-arm 10.1 now compiles ulab + MicroPython.
=> Fix Incompatibility between gcc-arm 10.1 and ulab + MicroPython

code/create.c
Fix for 'ulab.arange()' code in 'create.c', due to missing MICROPY_FLOAT_C_FUN(ceil).
So it compiles not only on 'ports/unix' and on 'ports/stm32' (etc) with DP (double precision), but also on 'ports/stm32' (etc) with SP (single precision).
=> fix arange : missing MICROPY_FLOAT_C_FUN(ceil) in create.c

code/linalg.c
Extend 'ulab.linalg.dot' to accept 2 vectors, so it becomres more similar to [`numpy.dot`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html?highlight=numpy%20dot) and the 1st case from the documentation will be accepted :
- If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).
besides the 2nd one :
If both a and b are 2-D arrays, it is matrix multiplication, ...
=> linalg.dot : also accepts 2 vectors of same dimension

code/ndarray.c
CircuitPython doc build fails with this diagnostic:
```
/home/runner/work/circuitpython/circuitpython/shared-bindings/ulab/index.rst:220:'any' reference target not found: List[float]
```
Use double backticks instead of single backticks to differentiate between
a reference to a type and just "show in monospace font".
See https://github.com/adafruit/circuitpython/pull/3602 and https://github.com/adafruit/circuitpython/pull/3602/checks?check_run_id=1302834010
=> Fix doc build problem in CircuitPython

code/ulab.c, code/ulab.h, code/ulab_create.c, code/ulab_create.h, docs/manual/extract_pyi.py, docs/ulab-change-log.md
should close https://github.com/v923z/micropython-ulab/issues/187
=> added diagonal and updated extract_pyi from circuitpython

.gitignore, build-cp.sh, build.sh, run-tests
Take our own version of run-tests
This is modified to better suit our needs, and because micropython
changes in the meantime were troublesome.
Expected outputs can be generated:
./run-tests -d tests --write-exp
Remove any incorrect .exp files before running as they won't be updated
otherwise.
=> Own run tests

code/ulab_create.c
Without this, circuitpython doesn't succeed at `make check-stubs` during its build process:
```
circuitpython-stubs/ulab/__init__.pyi:320: error: Function is missing a type annotation for one or more arguments
```
=> frombuffer: Add type declarations to stubs

code/ulab_create.c
A newline is required here for the markup to be vaild.
```
.../ulab/index.rst:426:Explicit markup ends without a blank line; unexpected unindent.
```
=> Fix doc build error

code/ulab.c, code/user/user.c, code/user/user.h
Solves the issue that constants (e.g. `ULAB_USER_MODULE` -> `ULAB_HAS_USER_MODULE`) have changed, preventing to include `/user/user.c`.
=> fix to allow including user.c

tests/numpy/isinf.py, tests/numpy/isinf.py.exp
I pretty much just copied the examples from your documentation for the tests and added one more example for extremely large float literals. Hopefully this wraps up #274 , I couldn't think of what else to add at the time being.
=> Add `np.isinf` tests

tests/numpy/linalg.py, tests/numpy/linalg.py.exp
Fails on high tolerance if result is >10?
=> Add vector 2-norm test

code/ulab.c, code/ulab_create.c, docs/ulab-change-log.md
`frombuffer` created a new array, contrary to the `numpy` specifications. This led to extra allocation of RAM, and consequently, speed penalty.
=> fixes frombuffer implementation glitch

code/ndarray.c, code/ulab.c, code/ulab_create.c, docs/ulab-change-log.md
fixes errors first found on the `legacy` branch: https://github.com/v923z/micropython-ulab/issues/331, https://github.com/v923z/micropython-ulab/issues/328
=> fix ndarray_is_dense, eye, ones, full, and zeros for Boolean type

README.md
I added instructions for compiling the firmware on the rp2 port (as requested).
=> :pencil: Add rp2 firmware instructions

code/usermod.cmake
This change introduces `usermod.cmake`, the CMake configuration required to make this library compatible with the CMake build systems for the rp2 (Raspberry Pi Pico/RP2040) and esp32 ports of MicroPython.
This is effectively 1:1 in functionality with `micropython.mk` and defines the source files, include directories and compile arguments needed to build the module.
See https://github.com/micropython/micropython/pull/6960 for discussion.
This is raised as a draft since the supporting framework has not yet been merged into MicroPython.
=> USER_C_MODULES cmake support for rp2 and esp32

README.md, build/rp2.sh
The `USER_C_MODULE` support for `cmake`-based ports is now upstream :sparkle: and this PR should update the documentation and build script to reflect this!
=> Update RP2 build script and README instructions

code/numpy/numpy.c
Representation of float objects depends on MICROPY_OBJ_REPR.  The original implementation of math constants (ulab.numpy.pi and etc.) works for MICROPY_OBJ_REPR = A and B.  It is extended to work with MICROPY_OBJ_REPR = C and D.  Note that CircuitPython basically employs MICROPY_OBJ_REPR_C, so that ulab constants give wrong numbers.
=> Fix implementation of math constants (e, inf, nan, pi).

code/ndarray.c, code/ulab.c, docs/ulab-change-log.md
This PR partially solves the issue discovered in https://github.com/v923z/micropython-ulab/issues/389: if an empty iterable is passed to the constructor, a proper `ndarray` will now be created; printouts are also fixed.
=> fix array initialisation with empty iterables

code/ndarray.c, code/ulab.c, docs/ulab-change-log.md
This PR factors out the array creation function, if the input is a generic iterable. This should allow most functions to take iterables, even if the body of the function expects an `ndarray`: if the input is an iterable, then it will automatically be converted to an `ndarray`. At the same time, we can also remove type exceptions from these functions.
=> factor out array creation from iterables

code/ndarray.c, code/ndarray.h, code/ndarray_properties.c, code/ulab.c, docs/manual/source/conf.py, docs/manual/source/ulab-ndarray.rst, docs/ulab-change-log.md, docs/ulab-convert.ipynb, docs/ulab-ndarray.ipynb
This PR implements direct assignment to `ndarray.shape`.
=> implement ndarray.shape assignment

code/ndarray.h, code/numpy/vector/vector.c, code/scipy/optimize/optimize.c, code/ulab.c
In CircuitPython, we are working on flash memory savings by "splitting" type objects. These changes support the new split type objects, while also being compatible with implementations that do not have this optimization.
=> support circuitpython-style split type objects

code/ndarray.c, code/ndarray_properties.c, code/numpy/numerical.c, code/numpy/numerical.h, code/numpy/numpy.c, code/numpy/transform.c, code/ulab.c, code/ulab.h, code/ulab_create.c, docs/ulab-change-log.md
This PR re-introduces the option of compiling with ULAB_MAX_DIMS = 1, and should close https://github.com/v923z/micropython-ulab/issues/430 .
=> fix compilation for 1D

code/numpy/compare.c, code/ulab.c, docs/ulab-change-log.md
This PR fixes the following failure in ulab.numpy.maximum (and etc., observed in CircuitPython 7.0).
```
>>> np.maximum(np.ndarray([1000], dtype = np.uint16), 10.0)
array([232.0], dtype=float32)
>>> np.maximum(np.ndarray([-1000], dtype = np.int16), 10.0)
array([64536.0], dtype=float32)
```
=> Fix compare between (uint16|int16) vs float.

build/esp32-cmake.sh
esp32-cmake.sh was building the firmware without the ulab module because it was not patching the Make**f**ile, but trying to patch the nonexistent Make**F**ile.
=> Fix Makefile misspelling

.readthedocs.yaml, README.md
This should replace all settings from readthedocs.org. This is the recommended approach, as it's controlled by versions then.
This version is built at: https://micropython-ulab-robert.readthedocs.io/en/feature-rtd_config/
Relates to #443
=> Created .readthedocs.yaml config file for latest versions

.readthedocs.yaml, docs/manual/source/conf.py
New branch needs to be created and PR needs to be retargeted.
Example build is here: https://micropython-ulab-robert.readthedocs.io/en/1.7.9/
Relates to #443
=> Adding branch release/v1.7 to suit version 1.7.9

.readthedocs.yaml
I don't think I can create a new branch from a PR. This should be merged into a new branch `release/v0.36` and the tip of the branch should be tagged as `0.36.1`.
Example build can be found in https://micropython-ulab-robert.readthedocs.io/en/0.36.1 .
Relates to #443
=> Adding branch release/v0.36 to suit version 0.36.1

.github/workflows/build.yml, .readthedocs.yaml, build-cp.sh, code/ndarray.c
Again, a new branch needs to be created first and this PR needs to be retargeted.
Example built is here: https://micropython-ulab-robert.readthedocs.io/en/0.54.6/
Relates to #443
=> Adding branch release/v0.54 to suit version 0.54.6

code/ndarray.c, code/ulab.c, docs/ulab-change-log.md
This PR should fix https://github.com/v923z/micropython-ulab/issues/454
=> fix ndarray_shape for arrays of zero length

code/numpy/numerical.c
mypy 0.920 started giving an error stating
```
ulab/numpy/__init__.pyi:51: error: Cannot assign multiple types to name "_float" without an explicit "Type[...]" annotation
ulab/numpy/__init__.pyi:54: error: Cannot assign multiple types to name "_bool" without an explicit "Type[...]" annotation
```
this quiets the error, and is also compatible with the previous version
(0.910).
=> Change how we alias the float and bool types for mypy

snippets/json_to_ndarray.py, snippets/ndarray_to_json.py
This PR adds two snippets, with which one can convert ndarrays to serialised json string, and vice versa. This should address the issue mentioned in https://github.com/v923z/micropython-ulab/issues/468#issuecomment-1012372905 and thereafter, and should also close https://github.com/v923z/micropython-ulab/issues/476.
=> json snippets

code/ndarray.c, code/ulab.c, docs/ulab-change-log.md
Should address the issue mentioned in https://github.com/v923z/micropython-ulab/issues/487
=> fix ndarray_copy_view for Boolean dtypes

build.sh, code/ulab.c, docs/ulab-change-log.md
This PR only adds the optional ULAB_HASH compile-time constant that, when defined, can be retrieved as `ulab.__sha__`.
=> add ULAB_HASH

code/ndarray.c
Prior to this change, if you built ulab with the default 2 dimensions and ran code that needed more than 2 (eg `tests/4d/complex/imag_real.py`) it would error out with the confusing message "ValueError: maximum number of dimensions is 4".
=> Fix error message for maximum number of dimensions

.github/workflows/build.yml, build.sh, code/ndarray.c, code/ndarray.h, code/ndarray_operators.c, code/numpy/approx.c, code/numpy/compare.c, code/numpy/create.c, code/numpy/fft/fft.c, code/numpy/fft/fft_tools.c, code/numpy/filter.c, code/numpy/io/io.c, code/numpy/linalg/linalg.c, code/numpy/ndarray/ndarray_iter.c, code/numpy/numerical.c, code/numpy/numpy.c, code/numpy/transform.c, code/numpy/vector.c, code/scipy/linalg/linalg.c, code/scipy/optimize/optimize.c, code/scipy/scipy.c, code/scipy/signal/signal.c, code/scipy/special/special.c, code/ulab.c, code/utils/utils.c
ulab currently does not compile when `MICROPY_OBJ_REPR_D` is selected as the object representation.  This representation is useful when you don't want float objects to use heap memory (they are allocated in-place, like small ints).
This PR fixes ulab so it does build with this option.  The main items fixed are:
- consistent use of `MP_ROM_QSTR` and `MP_ROM_PTR` in defining locals/modules dicts
- use of `MP_ROM_NONE` etc in `allowed_args` arrays
- consistent use of `MP_OBJ_TO_PTR` and `MP_OBJ_FROM_PTR`
- fix use of float literal constants
@v923z is this something you're interested in having?  In my opinion it's a good improvement and should not change in anyway the existing non-obj-repr-D builds.
=> Fix build for MICROPY_OBJ_REPR_D configurations

build-cp.sh, build.sh, code/numpy/fft/fft.c, code/numpy/fft/fft.h, code/numpy/io/io.c, code/numpy/linalg/linalg.c, code/numpy/linalg/linalg.h, code/numpy/numpy.c, code/numpy/numpy.h, code/scipy/linalg/linalg.c, code/scipy/linalg/linalg.h, code/scipy/optimize/optimize.c, code/scipy/optimize/optimize.h, code/scipy/scipy.c, code/scipy/scipy.h, code/scipy/signal/signal.c, code/scipy/signal/signal.h, code/scipy/special/special.c, code/scipy/special/special.h, code/ulab.c, code/user/user.c, code/user/user.h, code/utils/utils.c, code/utils/utils.h
These errors actually occurred when building the raspberry pi pico port; they weren't deteted when building the unix port during ulab ci, as this does not enable the diagnostics -Werror=undefined or -Werror=discarded-qualifiers.
=> Fix several build errors in CircuitPython

build.sh, code/ndarray.h, code/numpy/approx.c, code/numpy/create.c, code/numpy/numpy.c, code/scipy/optimize/optimize.c
=> fix use of MICROPY_FLOAT_CONST, and build single-precision as part of CI

tests/2d/numpy/nonzero.py, tests/2d/numpy/nonzero.py.exp
added following script at `ulab/tests/2d/numpy/nonzero.py`
```python
try:
from ulab import numpy as np
except:
import numpy as np
array = np.array(range(16)).reshape((4,4))
boolean_array = array < 3
row_indices, column_indices = np.nonzero(boolean_array)
print("Given Array:\n", array)
print("\nBoolean Array:\n", boolean_array)
print("\nFollowing indices have non-zero values:")
for i in range(len(row_indices)):
print("row", row_indices[i], "and column", column_indices[i])
```
The expected output file is located at `ulab/tests/2d/numpy/nonzero.py.exp`
Expected output:
```
Given Array:
array([[0.0, 1.0, 2.0, 3.0],
[4.0, 5.0, 6.0, 7.0],
[8.0, 9.0, 10.0, 11.0],
[12.0, 13.0, 14.0, 15.0]], dtype=float64)
Boolean Array:
array([[True, True, True, False],
[False, False, False, False],
[False, …
```
=> Added test script for np.nonzero()

code/numpy/vector.c, code/ulab.c, docs/ulab-change-log.md
Fixes https://github.com/v923z/micropython-ulab/issues/545
=> fix how arctan2 treats scalars

code/ulab.c
=> code/ulab.c: Fix missing comma in ulab_dtype_type definition.

.github/workflows/build.yml
CircuitPython now requires 3.9 as a minumum
=> Use python 3.10 during ci

code/numpy/numerical.c, tests/2d/numpy/sort.py.exp
Prior to this fix the code was using the mp_float_t data type for uint16 and producing incorrect sort results.
=> Fix sort when dtype is uint16

code/numpy/transform.c
Before, it was erroneously allocated as a 1-element array instead of a 6-element array in the test case.
Closes #574
=> Allocate 1d results of correct size

code/ndarray.c, code/ulab.c, docs/ulab-change-log.md, tests/2d/numpy/zeros.py, tests/2d/numpy/zeros.py.exp
Now, requesting to allocate an array directly from .ones() or .zeros() that is too big gives the exception 'array is too big', like numpy.
This does depend on a gcc extension, `__builtin_mul_overflow`, present since at least version 5. This extension is also supported in clang. msvc is probably the only compiler of note that does not support it.
Closes: #576
There are still a few suspicious allocations of multiplied sizes elsewhere, e.g., this one from poly.c:
```c
XT = m_new(mp_float_t, (deg+1)*leny); // XT is a matrix of shape (deg+1, len) (rows, columns)                                                                                             
```
there are also some allocations of square arrays that are the same size as square arrays that already exist, so no overflow checking would …
=> Check that array size doesn't overflow at construction time

code/ndarray.h
Older compilers (eg for esp8266) cannot see that "const uint32_t" is a true constant at compile time, so use an assigned enum instead.
Don't do this for object representation D because that requires a 64-bit integer.
=> Use enum instead of const for float consts with repr C

README.md, build/rp2w.sh
In v923z/micropython-ulab, `build/rp2.sh` works fine for Raspberry Pi Pico but doesn't work for Pico W (the latest board with WiFi capability).
* I newly added a build script `build/rp2w.sh` for Pico W users.
* I also added a link in `README.md` to access the script.
=> Add a build script for Raspberry Pi Pico W

code/numpy/compare.c
A very small change to fix a warning when building with some features deactivated.
=> Fix unused function compare_equal_helper warning

code/numpy/create.c, code/ulab.c, tests/2d/numpy/arange.py, tests/2d/numpy/arange.py.exp
Inputing `np.arange(0,np.nan)` crashes
=> Fix arange crashing when start, stop or step is nan

code/ndarray.c, code/ulab.c, docs/ulab-change-log.md
Fixes the issue mentioned in https://github.com/v923z/micropython-ulab/issues/589
=> ndarray_from_mp_obj correctly treats Booleans

code/numpy/numpy.c, code/numpy/vector.c, code/numpy/vector.h, code/ulab.h, requirements_cp_dev.txt
This is useful for generating FIR filters using code snippets generated at https://fiiir.com/ (at least those with a rectangular window type; other window types need additional functions but we can revisit it later if needed)
I think this will come in handy for folks who are using the advanced features of our audio synthesizer module, synthio.
e.g., the following block now gives highly similar results on ulab or numpy:
```py
try:
import numpy as np
except:
from ulab import numpy as np
fS = 48000  # Sampling rate.
fL = 4000  # Cutoff frequency.
N = 23  # Filter length, must be odd.
h = np.sinc(2 * fL / fS * (np.arange(N) - (N - 1) / 2))
h /= np.sum(h)
=> ulab.numpy: implement sinc for creating audio filters

.github/workflows/build.yml, code/numpy/vector.c, code/numpy/vector.h, code/ulab.c, code/ulab.h
This PR adds the `out` keyword argument to functions implemented in vector.c. These are the universal `numpy` functions.
=> add the out keyword argument to universal functions

build-cp.sh
In https://github.com/adafruit/circuitpython/pull/8070 we changed the commands for fetching submodules.
from what I can see, fetch-all-submodules is what fetch-submodules was; this is more than strictly necessary but should be the smallest change to get ulab building again.
This is trying to fix the underlying the cause of the build failure seen in #625
=> fix fetching submodules (cp build process change)

code/ndarray.c, code/numpy/create.c, code/numpy/poly.c, code/ulab.c
Fix multiple problems due to overflowing of int types + infinite arange
Also @v923z is there a way to contact you via email ? You can send me one at felix.richart@numworks.com ! Thanks a lot.
=> Int overflow

code/numpy/vector.c, code/ulab.c, docs/ulab-change-log.md
`o_in` is only used in the SUPPORTS_COMPLEX case, so the variable definition needs to be moved accordingly.
=> Fix -Wunused-variable diagnostic when !ULAB_SUPPORTS_COMPLEX

code/numpy/vector.c, tests/1d/numpy/universal_functions.py, tests/1d/numpy/universal_functions.py.exp
Fixes https://github.com/v923z/micropython-ulab/issues/635
Verified by re-compiling circuitpython with this change.
=> numpy/vector.c: remove usage of fpclassify

code/numpy/compare.c, code/numpy/numerical.c, code/numpy/vector.c
- Add type annotations for functions in compare.c
- Update annotations in vector.c to match behavior
This should address at least the specific issues noted in https://github.com/adafruit/circuitpython/issues/8715 and https://github.com/v923z/micropython-ulab/issues/662 . (As I'd filed the original issue here for a more localized docubug :smile:) please of course feel free to re-purpose the issue, or close it to start a new generic tracking issue later as seems appropriate.
=> Update type annotations in compare.c and vector.c

code/numpy/io/io.c, code/ulab.c, docs/ulab-change-log.md
Fixes the issue mentioned in https://github.com/v923z/micropython-ulab/discussions/665.
=> fix loadtxt for the case, when built-in complexes are not supported

.github/workflows/build.yml, build-cp.sh
Notably bumps Python to prevent macOS builds failing, and bumps "checkout" and "setup-python" versions to avoid deprecation warnings.
Tests/builds still seem to be failing so I've also enabled "continue-on-error" to try and make it run *all* the tests - for a better picture of what's failing and where- but seem to have failed to make this work across both MicroPython and CircuitPython tests.
=> CI: Update some deprecated dependency versions

README.md
UInfortunately Pycom is no longer a thing, removed from the platforms list.
=> Removed Pycom reference

docs/ulab-ndarray.ipynb
The value of `a[a < 5]` should be referred to as `"a[a < 5]"`, not `"a < 5"`, because `a < 5` has a different value.
=> Correct `"a[a < 5]"` in ulab-ndarray.ipynb

code/numpy/carray/carray.c
Very tiny PR :)
Noticed this while looking though CircuitPython's typing issues.
Might as well hint `real()` and `imag()` with `builtins.complex` too, but since it seems not to be supported yet, decided to only hint the supported types even though it contradicts the docstrings.
=> Add missing type hints to `carray`

code/numpy/random/random.c
In `numpy/random.c`:
The preprocessor guard for `MICROPY_PY_RANDOM_SEED_INIT_FUNC` was not complete: the value was used even if it was undefined.
There were also inconsequential trailing spaces and a trailing newline that were cleaned up by emacs when I edited the file.
=> numpy/random.c: fix use of MICROPY_PY_RANDOM_SEED_INIT_FUNC

code/ulab.c, code/utils/utils.c, docs/ulab-change-log.md
Fixes a compilation error, when complexes are supported, but the FFT is not `numpy`-compatible.
=> fix compilation error for complexes

code/numpy/numerical.c, code/ulab.c, docs/manual/source/conf.py, docs/ulab-change-log.md, docs/ulab-convert.ipynb, docs/ulab-numerical.ipynb
Addresses the issue raised in https://github.com/v923z/micropython-ulab/issues/705
=> ix keepdims for min, max, argmin, argmax

README.md
We include `ulab` in TulipCC, thank for for the great work! Try it at https://tulip.computer/run/
A webassembly example of AMY/Tulip using Tulip : https://shorepine.github.io/amy/piano.html
=> Adding tulipcc to ulab's users

code/scipy/integrate/integrate.c, code/ulab.c, docs/ulab-change-log.md
Fixes the issue raised in https://github.com/v923z/micropython-ulab/issues/713
=> re-name integration constants

code/ndarray.c, code/ndarray.h, code/numpy/compare.c, code/numpy/io/io.c, code/numpy/poly.c, code/numpy/vector.c, code/ulab.c, docs/ulab-change-log.md
Fixes the issue mentioned in https://github.com/v923z/micropython-ulab/issues/706
=> loadtxt can deal with multi-line comments

code/ndarray.c, code/ndarray.h, code/ndarray_properties.c, code/ndarray_properties.h, code/ulab.c, code/ulab.h
Adds `ndim` as requested in https://github.com/v923z/micropython-ulab/issues/721.
=> add ndim property
