code/filter.c

Special casing floats decreases runtime to about 45% of original (applying a 117-tap filter to 512 points of data goes from 70ms to 32ms)
The top_n/bot_n calculations already meant that the a/c indices were never out of range.  This decreases runtime further to about 15% of original (11ms)
Timings done on an Adafruit Clue (nrf52840 at 64MHz)
It does of course increase code size somewhat.  It would be possible to put the all-float case inside an `ifdef` if that's a tradeoff you want to offer to users of ulab.

convolve: Optimize and special-case floats

---

code/filter.c

My earlier change introduced a build error, at least under circuitpython.  I'm not sure why I didn't find this before making the pull request, sorry for the trouble.

filter_convolve: fix build error

---

code/ulab.c

Enable properties and sort() in circuitpython

Ndarray properties sort

---

code/linalg.c
docs/manual/source/conf.py
docs/manual/source/ulab.rst
docs/ulab-manual.ipynb

The update to the documentation should fix https://github.com/v923z/micropython-ulab/issues/58, while the Cholesky decomposition implements the feature request in https://github.com/v923z/micropython-ulab/issues/42.

added Cholesky decomposition to linalg.c, updated documentation

---

code/ndarray.c
code/ulab.c
code/vectorise.c
docs/manual/source/conf.py
docs/manual/source/ulab.rst
docs/ulab-change-log.md
docs/ulab-manual.ipynb

This PR should also fix https://github.com/v923z/micropython-ulab/issues/61

added around to the vector sub-module, and extended ndarray initialisation options

---

code/ndarray.c
code/ndarray.h
tests/slicing2.py

Also adds a new test.  The test passes both on micropython and circuitpython.

Add to #68 for CircuitPython compatibility

---

code/ndarray.c

This modification should fix https://github.com/v923z/micropython-ulab/issues/73.

added unistd.h to ndarray.c to fix issue #73

---

code/linalg.c
docs/ulab-change-log.md

This PR fixes the indexing error that triggers https://github.com/v923z/micropython-ulab/issues/94

fix indexing error in linalg.dot

---

code/ndarray.h
code/ulab.c
docs/ulab-change-log.md

fixed compilation error in issue #98

---

code/ndarray.c
docs/ulab-change-log.md

Fixes https://github.com/v923z/micropython-ulab/issues/117

fix for issue 117

---

code/numerical.c
code/ulab.c
docs/ulab-change-log.md

This PR should fix the issue mentioned in https://github.com/adafruit/circuitpython/issues/2984

fixes min/max error from adafruit/circuitpython #2984

---

code/ndarray.c
code/ndarray.h
code/ulab.c
docs/ulab-change-log.md

This PR should fix the issue in https://github.com/v923z/micropython-ulab/issues/124

fixes compilation error in openmv

---

code/approx.h
code/create.c
code/create.h
code/ndarray.h
code/ulab.c

This PR should close the feature request: https://github.com/v923z/micropython-ulab/issues/139

add arange

---

code/create.c
code/ulab.c
docs/ulab-change-log.md

Fixes the issue reported in https://github.com/v923z/micropython-ulab/issues/139

fixed arange

---

code/approx/approx.c
code/compare/compare.c
code/linalg/linalg.c
code/numerical/numerical.c
code/poly/poly.c

Re-arranged the functions in all modules, so that the order in the `circuitpython` documentation is alphabetical.

Documentation

---

code/ndarray.c
code/vector/vectorise.c

I found some paragraphs are mistakenly joined (by lacking empty lines).

Minor fixes on Python stubs

---

code/linalg/linalg.c

This fix https://github.com/v923z/micropython-ulab/issues/173
And the accuracy was pretty good compare to numpy.

Fix diagonal 0 error in row-reduction process

---

code/approx/approx.c
code/ndarray.c
code/ulab.c
code/ulab_create.c
docs/ulab-change-log.md

Fixes mysterious indexing error, when the index is a float.

Slice patch

---

.github/workflows/build.yml
build-cp.sh
code/ndarray.c

This includes #185 so we can hopefully see if the problem is truly resolved.

Build circuitpython-ulab as part of CI

---

code/numerical/numerical.c
code/ulab.c
docs/ulab-change-log.md

should fix https://github.com/v923z/micropython-ulab/issues/195

fixed small error in argmin_argmax

---

code/ndarray.c
code/ulab.c
docs/manual/source/conf.py
docs/ulab-change-log.md
docs/ulab-convert.ipynb

Should fix the issue mentioned in https://github.com/v923z/micropython-ulab/issues/195

fixed initialisation error in ndarray_make_new_core

---

code/linalg/linalg.c
code/ndarray.c
code/ulab.c
docs/ulab-change-log.md

This PR should fix https://github.com/v923z/micropython-ulab/issues/200

fixed iteration loop in norm, shape

---

code/numerical/numerical.c
code/numerical/numerical.h
code/ulab.c
code/ulab.h
docs/manual/source/conf.py
docs/manual/source/ulab-intro.rst
docs/manual/source/ulab-ndarray.rst
docs/manual/source/ulab-numerical.rst
docs/manual/source/ulab-programming.rst
docs/manual/source/ulab/numerical/index.rst
docs/ulab-change-log.md
docs/ulab-convert.ipynb
docs/ulab-numerical.ipynb

Should answer https://github.com/v923z/micropython-ulab/issues/189

implementation of the median function

---

code/numerical/numerical.c
code/numerical/numerical.h
code/ulab.c

Should fix the issues mentioned in https://github.com/v923z/micropython-ulab/issues/205

fixed indexing/array in numerical

---

code/ndarray.c
code/ulab.c
docs/ulab-change-log.md

Should fix issue mentioned in https://github.com/v923z/micropython-ulab/issues/208

fixes array casting glitch

---

code/ndarray.c
code/ulab.c
docs/ulab-change-log.md

This should patch the issue raised in https://github.com/v923z/micropython-ulab/issues/192

fixed slicing issues

---

code/ndarray.c
code/ulab.c
docs/ulab-change-log.md

Should fix https://github.com/v923z/micropython-ulab/issues/212

transpose fix

---

code/ndarray_operators.c
code/ndarray_operators.h
code/ulab.c
code/ulab.h
code/ulab_tools.c
code/ulab_tools.h
code/vector/vectorise.c
docs/ulab-change-log.md

This PR partially implements @jepler's suggestion on using function pointers to resolve C types.

Function pointer

---

code/linalg/linalg.c
code/ulab.c
docs/ulab-change-log.md

Should fix the sixth issue in https://github.com/v923z/micropython-ulab/issues/218

fixed indexing error in trace

---

code/ulab.c
code/ulab_create.c
docs/ulab-change-log.md

Should fix issue 17 in https://github.com/v923z/micropython-ulab/issues/218

swapped N, M in eye

---

code/approx/approx.c
code/ulab.c
docs/ulab-change-log.md

Should fix issue 15 in https://github.com/v923z/micropython-ulab/issues/218

fixed trapz

---

code/ndarray.c
code/ulab.c
docs/ulab-change-log.md

fixed dtype creation code

---

code/ndarray.c
code/ulab.c
code/ulab_create.c
docs/ulab-change-log.md

Should fix https://github.com/v923z/micropython-ulab/issues/232

implemented full/zeros/ones fix

---

code/numerical/numerical.c
code/ulab.c
docs/ulab-change-log.md

Fixes the issue reported in 7/8 of https://github.com/v923z/micropython-ulab/issues/218

fixed signedness problem in min/max

---

code/ndarray.c
code/ulab.c
docs/ulab-change-log.md

This PR pulls in @jepler's suggestion from https://github.com/v923z/micropython-ulab/pull/220#issuecomment-730416402

fixed testing error in ndarray

---

code/approx/approx.c
code/ulab.c
docs/ulab-change-log.md

Should fix issue 14 in https://github.com/v923z/micropython-ulab/issues/218

fixed interp

---

tests/numpy/approx.py
tests/numpy/approx.py.exp

This branch contains the script for testing:
1. np.interp
1. np.newton
1. np.bisect
1. np.fmin
1. np.trapz

add script for testing approx module

---

tests/numpy/universal_functions.py
tests/numpy/universal_functions.py.exp

The branch contains the script to test several functions in the universal module.

add script to test universal functions

---

code/linalg/linalg.c
code/ulab.c
docs/ulab-change-log.md

Should fix issue 10 in https://github.com/v923z/micropython-ulab/issues/218

fixed linalg.norm

---

tests/numpy/filter.py
tests/numpy/filter.py.exp

This branch contains script to test:
1. `np.convolve`
1. `np.sosfilt`

add script to test filter functions

---

tests/numpy/optim.py
tests/numpy/optim.py.exp

This branch contains script to test:
1. `np.newton`
1. `np.bisect`
1. `np.fmin`

add script to test numerical optimization functions

---

code/numerical/numerical.c
code/ulab.c
code/ulab.h
docs/ulab-change-log.md

Should address issue 16 in https://github.com/v923z/micropython-ulab/issues/218

added in-place sort

---

code/ulab.c
code/ulab.h
docs/ulab-change-log.md

Should close https://github.com/v923z/micropython-ulab/issues/249

added inf/nan class level constants

---

code/ndarray.c

Add `array.dtype` stub

---

code/numerical/numerical.c

Specify float literals as float

---

README.md

Should fix https://github.com/v923z/micropython-ulab/issues/273

updated readme.md with instructions for compiling for EPS32

---

code/ndarray.c
code/ndarray.h
code/numpy/numpy.c

Rename array to ndarray, replaced with constructor fn

---

code/numerical/numerical.h
code/ulab.c
docs/ulab-change-log.md

Should address the problem mentioned in https://github.com/v923z/micropython-ulab/issues/285.

fixes issue #285

---

code/numerical/numerical.c
code/ulab.c
code/ulab.h
docs/ulab-change-log.md

fixes the issue reported here: https://github.com/adafruit/circuitpython/issues/4086

fixed the calculation of the standard deviation on iterables

---

code/numpy/linalg/linalg.c
code/ulab.c
docs/ulab-change-log.md

improved accuracy of linalg.norm, and extended it to generic iterables

---

code/ndarray.c
code/numpy/linalg/linalg.c
code/numpy/linalg/linalg.h
code/numpy/numerical/numerical.c
code/numpy/numerical/numerical.h
code/ulab.c
code/ulab_tools.c
code/ulab_tools.h
docs/ulab-change-log.md

This PR should address the issue raised in https://github.com/v923z/micropython-ulab/issues/307

improved linalg.norm

---

code/numpy/transform/transform.c
code/ulab.c
docs/ulab-change-log.md

This PR addresses the issue raised in https://github.com/v923z/micropython-ulab/issues/315

fixed faulty dot function

---

code/ulab.c
code/ulab_create.c
docs/ulab-change-log.md

Should fix https://github.com/v923z/micropython-ulab/issues/331

fix eye, ones, full, zeros for bool dtype

---

code/linalg/linalg.c
code/ulab.c
docs/ulab-change-log.md

backport of fix for issue https://github.com/v923z/micropython-ulab/issues/315

backporting fix for dot function

---

code/numpy/transform/transform.c
code/ulab.c
docs/ulab-change-log.md

Should fix the issue first reported in https://github.com/adafruit/circuitpython/issues/4250

fix dot function

---

code/linalg/linalg.c
code/ulab.c
docs/ulab-change-log.md

Should fix dot multiplication issue reported in https://github.com/adafruit/circuitpython/issues/4250

fix linalg.dot

---

code/ulab.c
code/ulab_create.c
docs/ulab-change-log.md

This PR addresses that issue in https://github.com/v923z/micropython-ulab/issues/331

fix linspace/logspace/arange for Boolean dtypes

---

tests/numpy/any_all.py
tests/numpy/any_all.py.exp

This PR should resolve the last remaining issue in https://github.com/v923z/micropython-ulab/issues/276

add any/all test script

---

README.md
code/numpy/numerical/numerical.c

This PR should fix https://github.com/v923z/micropython-ulab/issues/349

fix ESP32 compilation error and instructions

---

build/esp32.sh

This PR adds build scripts for various ports

add build script for esp32

---

snippets/rclass.py

This PR should add the class implementation from https://github.com/v923z/micropython-ulab/issues/278

add rclass

---

code/ndarray.c
code/ndarray.h
code/numpy/numpy.h
code/scipy/scipy.h
code/scipy/signal/signal.h
code/scipy/special/special.h
code/user/user.h
code/utils/utils.h

The legacy build had worked for me with ArduPy (micropython v1.11) but for compatibility with other HW which uses ulab 2.1.5. i made some changes so it works for me again.
Maybe it works for other micropython versions, too.

Ardupy openmv

---

code/scipy/optimize/optimize.c
code/scipy/optimize/optimize.h
code/ulab.c
docs/ulab-change-log.md

This PR should fix the issue found in https://github.com/v923z/micropython-ulab/issues/373.

fix small glitch in optimize

---

README.md
build/esp32-cmake.sh

This PR updates the README, based on the comments in https://github.com/v923z/micropython-ulab/issues/372

update ESP32 compile instructions in readme

---

docs/manual/source/conf.py
docs/manual/source/index.rst
docs/manual/source/scipy-linalg.rst
docs/scipy-linalg.ipynb
docs/ulab-convert.ipynb

This PR adds the documentation for `scipy.linalg.solve_triangular`, as mentioned in https://github.com/v923z/micropython-ulab/issues/379

add docs for solve_triangular

---

code/numpy/numerical/numerical.c
code/ulab.c
docs/ulab-change-log.md

This PR fixes the nan return value.

fix nan return value

---

code/ulab.c
code/ulab_create.c
code/ulab_create.h
docs/ulab-change-log.md

cosmetic modification in the code, no functional change

initialise arange values via macro

---

code/numpy/approx/approx.c
code/ulab.c
docs/ulab-change-log.md

This PR updates exception strings in approx.c.

allow approx functions to take iterable arguments

---

docs/manual/source/conf.py
docs/manual/source/scipy-linalg.rst
docs/scipy-linalg.ipynb
docs/ulab-convert.ipynb

The PR adds only documentation, with no functional changes.

add cho_solve documentation

---

code/numpy/numpy.c
code/ulab.c
code/ulab.h
code/ulab_create.c
docs/manual/source/conf.py
docs/manual/source/ulab-ndarray.rst
docs/ulab-change-log.md
docs/ulab-ndarray.ipynb

This PR adds `empty` as an alias for `zeros`, and updates the documentation.

add empty, update docs

---

code/ndarray_properties.c
code/ulab.c
docs/manual/source/conf.py
docs/manual/source/ulab-ndarray.rst
docs/ulab-change-log.md
docs/ulab-convert.ipynb
docs/ulab-ndarray.ipynb

This PR adds the `T` property of the `ndarray`.

T transpose

---

code/scipy/linalg/linalg.c
code/ulab.c
docs/ulab-change-log.md

This PR fixes the compilation error reported in https://github.com/v923z/micropython-ulab/issues/413

fix float comparison in scipy/linalg.c

---

code/ulab.c

remove unused header imports

---

code/numpy/linalg/linalg.c
code/numpy/linalg/linalg.h
code/ulab.c
code/ulab.h
docs/ulab-change-log.md

This PR adds the implementation of the QR decomposition to the current master, and renders https://github.com/v923z/micropython-ulab/pull/371 obsolete.

add qr implementation

---

code/numpy/numerical.c
code/numpy/numerical.h
code/ulab.c
docs/ulab-change-log.md

This PR fixes the error reported in https://github.com/adafruit/circuitpython/issues/5033.

fix sum for 4D arrays

---

code/ndarray.c
code/numpy/fft/fft.c
code/scipy/linalg/linalg.c
code/scipy/signal/signal.c

This little trick was needed only temporarily, and can be removed.

remove temporary workaround

---

code/numpy/numerical.c
code/ulab.c
docs/ulab-change-log.md

Fixes the error reported in https://github.com/v923z/micropython-ulab/issues/459

fix any/all function

---

code/numpy/numerical.c
code/numpy/numerical.h
code/ulab.c
docs/ulab-change-log.md
tests/2d/numpy/sort.py
tests/2d/numpy/sort.py.exp

Consolidating https://github.com/v923z/micropython-ulab/pull/514 and https://github.com/v923z/micropython-ulab/pull/517

fix sorting on empty arrays

---

code/numpy/create.c
code/ulab.c
docs/ulab-change-log.md
tests/2d/numpy/concatenate.py
tests/2d/numpy/concatenate.py.exp

Fixes the issue raised in https://github.com/v923z/micropython-ulab/issues/572

fix concatenate

---

code/numpy/create.c
code/ulab.c
docs/ulab-change-log.md
tests/2d/numpy/arange.py
tests/2d/numpy/arange.py.exp

Should fix the issue raised in https://github.com/v923z/micropython-ulab/issues/580.

raise exception in arange, if step size is 0

---

code/ndarray.h
code/ndarray_properties.h
code/numpy/numerical.c

Add missing pre-processor constants conditions preventing the build if one deactivates some features.

Add missing constant constraints

---

code/ndarray_operators.c
code/ulab.c
docs/ulab-change-log.md

Should fix the issue raised in https://github.com/v923z/micropython-ulab/issues/610

fix binary division

---

code/ndarray.c
code/ulab.c
docs/ulab-change-log.md

Implements the feature requested in https://github.com/v923z/micropython-ulab/issues/608

implement unknown shape dimension in reshape

---

.github/workflows/build.yml

https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners

Per github docs, run apt-get update

---

code/ndarray.c
code/ndarray.h
code/numpy/create.c
code/numpy/numerical.c
code/ulab.c

ndarrays can now be created from a buffer, as requested in https://github.com/v923z/micropython-ulab/issues/676.

address issue raised in https://github.com/v923z/micropython-ulab/issues/676

---

README.md
code/ndarray.c
code/ndarray_operators.c
code/ndarray_operators.h
code/ulab.c
code/ulab.h
docs/ulab-ndarray.ipynb

Addresses the feature request in https://github.com/v923z/micropython-ulab/issues/732.

add modulo operator
